version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/node-app
    overwrite: true

permissions:
  - object: /var/www/myapp
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:


  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: application_stop.sh
      timeout: 300
      runas: root